#!/bin/bash
#
# launch_sample [--agent]
#
# A script to launch the SwingExplorer example from within a local
# development environment. This is a development tool only, to help
# debug the migration from Ant to Maven builds.
#
# For this to work, you must have swingexplorer-agent built and installed 
# in your local Maven repo, and swingexplorer-core built with `mvn package`. 

this_dir="$(dirname $0)"
this_dir="$(realpath $this_dir)"
core_dir="$(dirname $this_dir)"
repo_dir="$(dirname $core_dir)"

M2_REPO=$HOME/.m2/repository
VERSION="$(grep '<version>' ${repo_dir}/pom.xml | head -1 | sed -E -e 's/.*<version>//; s|</version>.*||')"

use_agent=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --agent)
        use_agent=1
        shift
        ;;
    *)
        ;;
  esac
done

agent_jar_file=$M2_REPO/org/swingexplorer/swingexplorer-agent/${VERSION}/swingexplorer-agent-${VERSION}.jar
agent_deps=$M2_REPO/javassist/javassist/3.12.1.GA/javassist-3.12.1.GA.jar
swexpl_deps=$M2_REPO/org/jdesktop/swing-layout/1.0.3/swing-layout-1.0.3.jar
if [[ "$use_agent" == 1 ]]; then
  JAVA_CLASSPATH=$core_dir/target/swingexplorer-core-${VERSION}.jar:${swexpl_deps}
  java -javaagent:${agent_jar_file} -Xbootclasspath/a:${agent_jar_file}:${agent_deps} -cp $JAVA_CLASSPATH org.swingexplorer.Launcher sample.FRMPerson  
else
	JAVA_CLASSPATH=${agent_jar_file}:${agent_deps}:$core_dir/target/swingexplorer-core-${VERSION}.jar:${swexpl_deps}
  java -cp $JAVA_CLASSPATH org.swingexplorer.Launcher sample.FRMPerson
fi